---
title: "Day 3 Afternoon Session"
author: "Tom Gibbens-Matsuyama"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Create some vectors in R

These are all character string elements
```{r}
# vectors must contain elements of the same data type ----
marmots <- c("blue", "green", 4, "yellow")

# return it ----
marmots

# 4 is technically a numerical value but R automatically put it as a character string
# because all vectors must have the same data type

# class ----
class(marmots)
```


These are all numeric elements
```{r}
pika <- c(12.4, 6.8, 2.9, 8.8, 5)
pika
class(pika)
```

These are all integer elements:
```{r}

# to make it a class "integer" put L at the end
bear <- c(20L, 3L, 5L, 18L, 23L)
bear
class(bear)

```


## Vector Math



```{r}
# Create some vectors ----
ringtail <- c(4.3, 8.9, 2.6, 7.1)
fox <- c(9.0, 12.5, 5.4, 10.9)

#add ----
ringtail + fox

#subtract ----
fox - ringtail

#scalar multiplier ----
100 * ringtail

# dot product ----
ringtail %*% fox
```

